apiVersion: apps/v1
kind: Deployment
metadata:
  name: "hello"
spec:
  replicas: 3  # Scale up as needed
  selector:
    matchLabels:
      app: "hello"
  template:
    metadata:
      labels:
        app: "hello"
    spec:
      containers:
        - name: "hello"
          image: "gcr.io/hello/jib-image"
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /health/readiness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health/liveness
              port: 8080
            initialDelaySeconds: 5
            timeoutSeconds: 3
            failureThreshold: 10
---
apiVersion: v1
kind: Service
metadata:
  name: "hello"
spec:
  selector:
    app: "hello"
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  sessionAffinity: None  # Ensure session affinity is disabled for round-robin
